[connections.snowflake]
account = "BZKPBZT-ZKB84361"
user = "DEVIPARVATHI"
authenticator = "externalbrowser"
password="Iamwinneralways@9",
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
